server {
    # nginx listens on a high port (>1024) which the non-root user can bind to.
    listen 8080; 

    root /usr/share/nginx/html;
    index index.html;

    # hides nginx version
    server_tokens off;

    # SPA Routing: Directs all unmatched requests to index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # block access to hidden files
    location ~ /\. {
        deny all;
    }
}